### ISSUE TITLE
[BUG] Ответ 200 OK при отправке PATCH api/v1/users/me/ на редактирования пользователя c удаленным полем email

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#100]
Тестовое окружение: https://skidivay.acceleratorpracticum.ru/

Шаги воспроизведения:
Отправить запрос POST /api/v1/cards/new-shop/ на создание карты нового магазина
В теле запроса:
{
  "name": "FA",
  "phone_number": "9286650888"
}

OР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - 200 OK
{
    "id": 175,
    "email": "FA123@m1.ru",
    "name": "FA",
    "phone_number": "9286650888"
}

**Comment by sldmxm** [comment]
Заголовок и содержимое не соответствуют друг другу.

Про заголовок. Patch - это частичное редактирование, достаточно указать одно поле, которое требуется поменять.
Про содержание. "POST /api/v1/cards/new-shop/ " не выдает 200 на такой запрос

**Comment by RollerDi** [comment]
Про содержание - надо быть осторожней, копируя шаблон задачи и внося в неё изменения=) конечно, запрос другой)
Поправьте в документации тогда, а то все поля на этот запрос стоят как обязательные, если я правильно понимаю

![Снимок9](https://github.com/Online-discount-card-service/osdc_backend/assets/148253752/ff50f87a-6119-44f4-806c-099e37c7e65c)

**Comment by sldmxm** [comment]
Документация формируется автоматически, в случае с patch это означает, что
за бы одно поле должно быть, это следует из метода
