### ISSUE TITLE
[BUG] Ошибка 201 Created при отправке POST api/v1/users/ на создание нового пользователя при вводе в поле "password" пароля с пробелом

### ISSUE THREAD

**Issue by EgorovMS** [Online-discount-card-service/osdc_backend#111]
Шаги воспроизведения:

Отправить запрос POST api/v1/users/ на создание нового пользователя

В теле запроса:

curl --location 'https://skidivay.acceleratorpracticum.ru/api/v1/users/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "skidivayOSDC1111@gmail.com",
    "name": "Иван",
    "phone_number": "9037651234",
    "password": "Qg5L l9b7"
}'

ОР: в ответе - сообщение об ошибке, код 400 Bad Request

ФР: в ответе - 201 created

{
    "id": 280,
    "email": "skidivayOSDC1111@gmail.com",
    "name": "Иван",
    "phone_number": "9037651234"
}

**Comment by Aenika** [comment]
Если я не ошибаюсь, ASCII включает в себя символ пробел.
