### ISSUE TITLE
[BUG] Ошибка 201 Created при отправке POST api/v1/users/ на создание нового пользователя при вводе в поле "password" пароля совпадающим с email

### ISSUE THREAD

**Issue by EgorovMS** [Online-discount-card-service/osdc_backend#112]
Шаги воспроизведения:

Отправить запрос POST api/v1/users/ на создание нового пользователя

В теле запроса:

curl --location 'https://skidivay.acceleratorpracticum.ru/api/v1/users/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "skidivayOSDC11111@gmail.com",
    "name": "Иван",
    "phone_number": "9037651234",
    "password": "skidivayOSDC11111@gmail.com"
}'

ОР: в ответе - сообщение об ошибке, код 400 Bad Request

ФР: в ответе - 201 created

{
    "id": 281,
    "email": "skidivayOSDC11111@gmail.com",
    "name": "Иван",
    "phone_number": "9037651234"
}

**Comment by Aenika** [comment]
А почему это должно быть ошибкой?
Наоборот, всё верно, это и должно работать.
Был запрос на презентации MVP: предупреждать юзера заранее обо всех ограничениях полей. Поскольку данное ограничение мы  не смогли красиво подключить на фронте, мы от него отказались.
Общее решение по ограничениям "совпадение полей почта и пароль" и "использование распространенного пароля" - отказаться от них.
