### ISSUE TITLE
[BUG] Ошибка 201 Created при отправке POST api/v1/users/set_password/ на смену пароля пользователя при вводе в поле "new_password" текущего пароля

### ISSUE THREAD

**Issue by EgorovMS** [Online-discount-card-service/osdc_backend#115]
Шаги воспроизведения:

Отправить запрос POST api/v1/users/set_password/ на пароля пользователя

В теле запроса:

curl --location 'https://skidivay.acceleratorpracticum.ru/api/v1/users/set_password/' \
--header 'Authorization: Token 3fd9344c52740c57e8311c72eaa90c23acd2c4c4' \
--header 'Content-Type: application/json' \
--data '{
    "new_password": "Qwerty1234",
    "current_password": "Qwerty1234"
}'

ОР: в ответе - сообщение об ошибке, код 400 Bad Request

ФР: в ответе - 204 No Content

**Comment by Aenika** [comment]
Это фича, для того, чтобы не "бесить" юзера. Да, у нас на бэке можно поменять пароль на точно такой же, чтобы не раздражать пользователя.
