### ISSUE TITLE
[BUG] Ошибка 400 Bad Request при отправке POST api/v1/cards/ на создание карты при вводе в поле "barcode_number" больше 40 символов

### ISSUE THREAD

**Issue by EgorovMS** [Online-discount-card-service/osdc_backend#116]
Шаги воспроизведения:
Отправить запрос POST api/v1/cards/ на создание карты
В теле запроса:
curl --location 'https://skidivay.acceleratorpracticum.ru/api/v1/cards/' \
--header 'authorization: Token 3fd9344c52740c57e8311c72eaa90c23acd2c4c4' \
--header 'Content-Type: application/json' \
--data '{
    "shop": "171",
    "name": "e",
    "card_number": "dcd GG123-_dcd GG123-_dcd GG123-_dcdff11",
    "barcode_number": "dcd GG123-_dcd GG123-_dcd GG123-_dcdfff11",
    "encoding_type": ""
}'
ОР: в ответе - 201 Created
ФР: в ответе - сообщение об ошибке, код 400 Bad Request
{
    "message": "Введены некорректные данные.",
    "detail": {
        "barcode_number": [
            "Номер штрих-кода может содержать только буквы, цифры, пробелы, тире и нижнее подчеркивание."
        ]

**Comment by Aenika** [comment]
Пофиксили, на сервере
