### ISSUE TITLE
[BUG] Ошибка 400 Bad Request при отправке POST api/v1/cards/new-shop/ на создание карты нового магазина при вводе в поле "name" специальные символы "!#$%&’*+/=?^_`{|}~-."

### ISSUE THREAD

**Issue by EgorovMS** [Online-discount-card-service/osdc_backend#123]
Шаги воспроизведения:

Отправить запрос POST api/v1/cards/new-shop/ на создание карты

В теле запроса:

curl --location 'https://skidivay.acceleratorpracticum.ru/api/v1/cards/new-shop/' \
--header 'Authorization: Token cef7ba8968669f7735f6d540ed4b1223b4f86a91' \
--header 'Content-Type: application/json' \
--data '{
  "shop": {
    "name": "kwjbv1",
    "group": [
      
    ]
  },
  "name": "kwjbv!#$%&’*+/=?^_`{|}~-.",
  "card_number": "и6782985762937",
  "barcode_number": "2097529067687",
   "encoding_type": ""
}'

ОР: в ответе - 201 Created

ФР: в ответе - сообщение об ошибке, код 400 Bad Request

{
    "message": "Введены некорректные данные.",
    "detail": {
        "name": [
            "Имя может содержать только буквы, пробелы и спецсимволы."
        ]
    }
}

**Comment by Aenika** [comment]
Аналогочино: символ ’ не входит в разрешенные символы по таблице.
Входят ' `
