### ISSUE TITLE
[BUG] Ответ 201 Created при отправке /api/v1/users/ запроса на создание пользователя, где поле password содержит кириллицу

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#27]
Шаги:
Отправить запрос Post/users на создание пользователя
В теле запроса:
{
"email": "pochta@gmail.com",
"username": "danil",
"phone_number": "9220401600",
"password": "Пароль999&"
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 201 created
{
"id": 3,
"email": "pochta@gmail.com",
"username": "danil",,
"phone_number": "9220401600"
}

![запись пользователя с паролем, содержащим кириллицу](https://github.com/Online-discount-card-service/osdc_backend/assets/148253752/f58bfa2d-3c25-435b-862f-9a304b2f7f76)

**Comment by Aenika** [comment]
![пароль_с_кириллицей](https://github.com/Online-discount-card-service/osdc_backend/assets/108528915/289cc551-f1a7-4565-bb15-955b944b6e15)
Исправлено
