### ISSUE TITLE
[BUG] Ответ 201 Created при отправке /api/v1/users/ запроса на создание пользователя, где поле username содержит цифры

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#28]
Шаги:
Отправить запрос Post/users на создание пользователя
В теле запроса:
{
  "email": "SKIDYVAY@test.com",
  "username": "12345",
  "phone_number": "9537734567",
  "password": "1k4jh12l4"
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 201 Created
{
  "id": 8,
  "email": "SKIDYVAY@test.com",
  "username": "12345",
  "phone_number": "9537734567"
}

![создание пользователя с username, содержащем цифры](https://github.com/Online-discount-card-service/osdc_backend/assets/148253752/f9472279-4cfb-4e3a-a05a-92c34bb7aef5)

**Comment by sldmxm** [comment]
username в текущей версии - это username, name появится сегодня
