### ISSUE TITLE
[BUG] Ответ 201 Created при отправке /api/v1/users/ запроса на создание пользователя, где поле password состоит только из букв латиницы

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#30]
Шаги:
Отправить запрос Post/users на создание пользователя
В теле запроса:
{
"email": "te@mail.ru",
"username": "Ant",
"phone_number": "9031234555",
"password": "iekdjfut"
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 201 created
{
"id": 9,
"email": "te@mail.ru",
"username": "Ant",
"phone_number": "9031234555"
}

![запись пользователя с паролем, состоящим только из букв латиницы — копия](https://github.com/Online-discount-card-service/osdc_backend/assets/148253752/17127041-3653-4667-9972-6a4da5fa6343)

**Comment by sldmxm** [comment]
Сделать шаблон для пароля через AUTH_PASSWORD_VALIDATORS в settings

**Comment by Aenika** [comment]
Исправлено
