### ISSUE TITLE
[BUG] Ответ 201 Created при отправке /api/v1/users/ запроса на создание пользователя, где поле email содержит кириллицу в доменной части

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#32]
Шаги:
Отправить запрос Post/users на создание пользователя
В теле запроса:
{
  "email": "skidyvay@тест.рф",
  "username": "Anna-Marie",
  "phone_number": "9031234567",
  "password": "1k4jh12l4"
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 201 Created
{
  "id": 2,
  "email": "skidyvay@тест.рф",
  "username": "Anna-Marie",
  "phone_number": "9031234567"
}

![создание пользователя с email с кириллицей в домене](https://github.com/Online-discount-card-service/osdc_backend/assets/148253752/e78dee45-f5c1-4686-b4b9-c79f8179c9b5)

**Comment by Aenika** [comment]
![почта_с_кириллицей](https://github.com/Online-discount-card-service/osdc_backend/assets/108528915/1eb7a947-ba43-44de-aab8-77c1c5e38763)
Исправлено
