### ISSUE TITLE
[BUG] Ответ 400 Bad Request при отправке /api/v1/users/ запроса на создание пользователя, где поле username содержит пробел

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#33]
Шаги:
Отправить запрос Post/users на создание пользователя
В теле запроса:
{
  "email": "yyyy@test.com",
  "username": "John Galt",
  "phone_number": "9035559517",
  "password": "1k4jh12l4"
}
ОР: в ответе - код 201 Created сообщение об ошибке
ФР: в ответе - сообщение об ошибке, код 400 Bad Request

**Comment by sldmxm** [comment]
username в текущей версии - это username, name появится сегодня
