### ISSUE TITLE
[BUG] Ответ 200 Ok при отправке /api/v1/auth/token/login/ запроса на авторизацию пользователя, где поле email содержит кириллицу в доменной части

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#34]
Шаги:
Отправить запрос Post/users на создание пользователя
В теле запроса:
{
  "email": "skidyvay@тест.рф",
  "password": "1k4jh12l4"
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 200 Ok
{
  "auth_token": "dbaa25618dd09f07bdc028ff66e757b14e46bcbb"
}

**Comment by Aenika** [comment]
Так как теперь нельзя зарегистрироваться с емейлом, содержащим кириллицу, то и залогиниться не получится
