### ISSUE TITLE
[BUG] Ответ 201 Created при отправке запроса POST /api/v1/cards/ на создание карты, где поле "shop" удалено в теле запроса

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#38]
Тестовое окружение: http://skidivay.acceleratorpracticum.ru/

Шаги воспроизведения:
Отправить запрос POST /api/v1/cards/ на создание карты
В теле запроса:
{
"name": "Магазин",
"card_number": "123456789",
"barcode_number": "",
"encoding_type": ""
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - 201 created
{
"id": 5,
"image": null,
"shop": null,
"name": "Магазин",
"pub_date": "2023-11-18T17:42:46.049742+03:00",
"card_number": "123456789",
"barcode_number": "",
"encoding_type": ""
}

**Comment by sldmxm** [comment]
Сделать поле магазина обязательным в модели Cards

**Comment by sldmxm** [comment]
Туда же https://github.com/Online-discount-card-service/osdc_backend/issues/37
