### ISSUE TITLE
[BUG] Ответ 200 Ok при отправке /api/v1/shops/ запроса неавторизированным пользователем на получение списка магазинов

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#49]
Тестовое окружение: http://skidivay.acceleratorpracticum.ru/
Шаги:
Отправить запрос GET/api/v1/shops/ на получение списка магазинов
ОР: в ответе - сообщение об ошибке, код 401 Unauthorized
ФР: в ответе - код 200 Ok
[
    {
        "id": 14,
        "group": [
            {
                "id": 1,
                "name": "Продукты"
            }
        ],
        "name": "KASSIR",
        "logo": "http://skidivay.acceleratorpracticum.ru/media/shop/04kassir_mUWOI40.png",
        "color": "#f8cc0b",
        "validation": true
    },
    {
        "id": 13,
        "group": [
            {
                "id": 1,
                "name": "Продукты"
            }
        ],
        "name": "METRO",
        "logo": "http://skidivay.acceleratorpracticum.ru/media/shop/05metro_V4A2b6g.png",
        "color": "#003c82",
        "validation": true
    },
    {
        "id": 15,
        "group": [
            {
                "id": 1,
                "name": "Продукты"
            }
        ],
        "name": "Лента",
        "logo": "http://skidivay.acceleratorpracticum.ru/media/shop/03lenta_ryLbEy5.png",
        "color": "#161c95",
        "validation": true
    },
    {
        "id": 12,
        "group": [
            {
                "id": 1,
                "name": "Продукты"
            }
        ],
        "name": "Магнит",
        "logo": "http://skidivay.acceleratorpracticum.ru/media/shop/06magnit_2Bmg6VY.png",
        "color": "#fc0000",
        "validation": true
    },
    {
        "id": 17,
        "group": [
            {
                "id": 1,
                "name": "Продукты"
            }
        ],
        "name": "Перекрёсток",
        "logo": "http://skidivay.acceleratorpracticum.ru/media/shop/01perekrestok_HmNUuQM.png",
        "color": "#005b29",
        "validation": true
    },
    {
        "id": 16,
        "group": [
            {
                "id": 1,
                "name": "Продукты"
            }
        ],
        "name": "Пятёрочка",
        "logo": "http://skidivay.acceleratorpracticum.ru/media/shop/02pyaterka_wpjHPtw.png",
        "color": "#d40304",
        "validation": true
    }
]

**Comment by sldmxm** [comment]
Они и должны выдавать неавторизованному пользователю, чтобы отображать карусель на экране авторизации
