### ISSUE TITLE
[BUG] Ответ 201 Created при отправке /api/v1/cards/ запроса на создание карты, где поле card_number содержит спецсимволы

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#51]
Тестовое окружение: http://skidivay.acceleratorpracticum.ru/
Шаги:
Отправить запрос POST/api/v1/cards/ на создание карты
{
    "shop": 16,
    "name": "Sh-p M.rk,t",
    "card_number": "!@#№$%",
    "barcode_number": "",
    "encoding_type": "ean-13"
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 201 Created
{
    "id": 69,
    "image": null,
    "shop": 16,
    "name": "Sh-p M.rk,t",
    "pub_date": "2023-11-20T15:34:56.418487+03:00",
    "card_number": "!@#№$%",
    "barcode_number": "",
    "encoding_type": "ean-13"
}

**Comment by Aenika** [comment]
Исправлено.
