### ISSUE TITLE
[BUG] Ответ 201 Created при отправке /api/v1/cards/ запроса на создание карты, где поле barcode_number содержит спецсимволы

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#55]
Тестовое окружение: http://skidivay.acceleratorpracticum.ru/
Шаги:
Отправить запрос POST/api/v1/cards/ на создание карты
{
    "shop": 16,
    "name": "Example",
    "card_number": "12345678987654321127",
    "barcode_number": "#$%^&",
    "encoding_type": "ean-13"
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 201 Created
{
    "id": 73,
    "image": null,
    "shop": 16,
    "name": "Example",
    "pub_date": "2023-11-20T15:52:48.539482+03:00",
    "card_number": "12345678987654321127",
    "barcode_number": "#$%^&",
    "encoding_type": "ean-13"
}

**Comment by Aenika** [comment]
Исправлено
