### ISSUE TITLE
[BUG] Ответ 201 Created при отправке /api/v1/cards/ запроса на создание карты без поля barcode_number

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#56]
Тестовое окружение: http://skidivay.acceleratorpracticum.ru/
Шаги:
Отправить запрос POST/api/v1/cards/ на создание карты
{
    "shop": 16,
    "name": "Ууу",
    "card_number": "12345678987654321127",
    "encoding_type": "ean-13"
}
ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 201 Created
{
    "id": 74,
    "image": null,
    "shop": 16,
    "name": "Ууу",
    "pub_date": "2023-11-20T16:03:29.589531+03:00",
    "card_number": "12345678987654321127",
    "barcode_number": "",
    "encoding_type": "ean-13"
}

**Comment by sldmxm** [comment]
Насколько я помню, договорились, что должен быть номер карты и/или номер штрих-кода
