### ISSUE TITLE
[BUG] Ответ 201 Created при отправке POST /api/v1/cards/new-shop/ на создание карты нового магазина, где поле "name" заполнено символами "?%№{}"

### ISSUE THREAD

**Issue by EgorovMS** [Online-discount-card-service/osdc_backend#65]
Тестовое окружение: https://skidivay.acceleratorpracticum.ru/

**Шаги воспроизведения:**
Отправить запрос POST /api/v1/cards/new-shop/ на создание карты нового магазина
В теле запроса:

{
"shop": {
"name": "string"
},
"name": "?%№{}",
"card_number": "123456789",
"barcode_number": "",
"encoding_type": ""
}

ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - 201 created

{
"id": 167,
"shop": {
"id": 60,
"group": [],
"logo": null,
"name": "string",
"color": "",
"validation": false
},
"image": null,
"name": "?%№{}",
"pub_date": "2023-11-23T20:29:05.468780+03:00",
"card_number": "123456789",
"barcode_number": "",
"encoding_type": "",
"usage_counter": 0
}

**Comment by Aenika** [comment]
Исправлено.
№ не пройдет, остальное по таблице - разрешенные спецсимволы
