### ISSUE TITLE
[BUG] Форма регистрации - блокируется регистрация пользователя, если в поле Пароль ввести валидное, но распространенное значение

### ISSUE THREAD

**Issue by Xalgina** [Online-discount-card-service/osdc_backend#83]
Шаги:

1. Перейти на https://skidivay.acceleratorpracticum.ru/
2. Нажать на кнопку "Войти"
3. Перейти во вкладку Регистрация
4. Заполнить поле Пароль валидным, но распространенным значением, например, Password1
5. Заполнить остальные поля валидными данными
6. Нажать на кнопку Далее

ОР: При вводе валидных данных в поле "Пароль" пользователь должен быть зарегистрирован. 
ФР: Не происходит регистрация пользователя, если введено валидное значение. Ответ сервера 400.

Окружение:
Xiaomi Redmi 9, Android 11, разрешение экрана 393x873. Google Chrome 119.0.6045.163
iOS 16.6.1, iPhone 14, 390 × 844, Safari

![image](https://github.com/Online-discount-card-service/osdc_backend/assets/148226806/4c7e6ead-69b6-4ab6-a330-665be97ab277)
![image](https://github.com/Online-discount-card-service/osdc_backend/assets/148226806/6eae673d-e567-45c8-811a-0fc386fb9e66)

**Comment by sldmxm** [comment]
Проверка убрана на беке
