### ISSUE TITLE
[BUG] Ответ 500 Internal Server Error при отправке POST api/v1/auth/token/login/ на авторизацию пользователя с паролем не совпадающем с тем, что был указан при регистрации

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#98]
Тестовое окружение: https://skidivay.acceleratorpracticum.ru/

Шаги:
1. Зарегистрироваться с учетными данными: {email: "sss@m.ru", password: "Lkj987!6"}
2. Отправить запрос POST /api/v1/auth/token/login/ на авторизацию пользователя с паролем не совпадающем с тем, что был указан при регистрации
{
  "password": "Lkj987!678",
  "email": "sss@m.ru"
}

ОР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - код 500 Internal Server Error
<!doctype html>
<html lang="en">
<head>
	<title>Server Error (500)</title>
</head>
<body>
	<h1>Server Error (500)</h1>
	<p></p>
</body>
</html>

![Снимок6](https://github.com/Online-discount-card-service/osdc_backend/assets/148253752/73eea633-4307-4f74-b5ad-b56035cd3a6a)
![Снимок5](https://github.com/Online-discount-card-service/osdc_backend/assets/148253752/750c8875-64fb-4ac9-a883-52ee11fc872c)
![Снимок4](https://github.com/Online-discount-card-service/osdc_backend/assets/148253752/433961f2-7761-449a-aceb-3767be2e692e)

**Comment by sldmxm** [comment]
Возможно, сервер обновлялся в это время. 
Если удастся повторить ошибку, имеет смысл приложить весь трейс
