### ISSUE TITLE
[BUG] Ответ 200 OK при отправке PATCH api/v1/users/me/ на редактирования пользователя c удаленным полем name

### ISSUE THREAD

**Issue by RollerDi** [Online-discount-card-service/osdc_backend#99]
Тестовое окружение: https://skidivay.acceleratorpracticum.ru/

Шаги воспроизведения:
Отправить запрос POST /api/v1/cards/new-shop/ на создание карты нового магазина
В теле запроса:
{
  "email": "FA123@m1.ru",
  "phone_number": "9286650888"
}
OР: в ответе - сообщение об ошибке, код 400 Bad Request
ФР: в ответе - 200 OK
{
    "id": 175,
    "email": "FA123@m1.ru",
    "name": "J",
    "phone_number": "9286650888"
}

**Comment by sldmxm** [comment]
Заголовок и содержимое не соответствуют друг другу.

Про заголовок. Patch - это частичное редактирование, достаточно указать одно поле, которое требуется поменять.
Про содержание. "POST /api/v1/cards/new-shop/ " не выдает 200 на такой запрос
